apiVersion: v1
kind: Service
metadata:
  name: ether-faucet-frontend-svc
  labels:
    project: ethernetes
spec:
  selector: 
    app: ether-faucet-frontend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80