apiVersion: v1
kind: Service
metadata:
  name: geth-member-node-svc
  labels:
    project: ethernetes
spec:
  selector: 
    app: geth-member-node-pod
  ports:
    - name: http-endpoint
      port: 8545
      targetPort: 8545
      protocol: TCP
    - name: ws-endpoint
      port: 8546
      targetPort: 8546
      protocol: TCP
    - name: auth-rpc
      port: 8551
      targetPort: 8551
      protocol: TCP
    - name: metrics
      port: 6060
      targetPort: 6060
      protocol: TCP
    - name: listener
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: discovery
      port: 30303
      targetPort: 30303
      protocol: UDP