apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-member-node-deployment
  labels:
    project: ethernetes
    app: geth-member-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth-member-node-pod
  template:
    metadata:
      labels:
        project: ethernetes
        app: geth-member-node-pod
    spec:
      initContainers:
      - name: geth-enode-retriever
        # image: appropriate/curl
        image: ubuntu
        command: 
        - "/bin/sh"
        - "-c"
        - "--"
        args:
        - |
          apt update && \
          apt install curl jq -y && \
          echo "Entering" && \
          ls -larth /shared-data-between-geth-nodes && \
          rm -f /shared-data-between-geth-nodes/execution-rw/enode.txt && \
          until curl -s http://geth-bootnode-svc:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"admin_nodeInfo","params":[],"id":1}' | jq -r '.result.enr' > /shared-data-between-geth-nodes/execution-rw/enode.txt ; do
            echo "Entered" && \
            echo "Waiting for Geth bootnode to start..." && \
            sleep 5
          done
        volumeMounts:
        - name: shared-data-between-geth-nodes
          mountPath: "/shared-data-between-geth-nodes"
        
      - name: init-execution-dir
        image: ubuntu
        command:
        - "/bin/sh"
        - "-c"
        - "--"
        args:
        - | 
          apt update && \
          apt install tree && \
          sleep 5 && \
          cp -r /shared-data-between-geth-nodes/execution-rw/* /execution && \
          echo "Printing /execution" && \
          ls -larth /execution && \
          chmod -R 777 /execution && \
          echo""
          echo "Content of /shared-data-between-geth-nodes"
          tree /shared-data-between-geth-nodes
          echo""
          echo "Dir /execution mode changed" && \
          mkdir -p /execution/keystore && \
          echo "Dir /execution/keystore created" && \
          ls -l /execution && \
          tree /execution
        volumeMounts:
        - name: shared-data
          mountPath: "/execution/"
        - name: shared-data-between-geth-nodes
          mountPath: "shared-data-between-geth-nodes"

      - name: geth-init
        image: docker.io/ethereum/client-go:v1.13.13
        args:
        - --datadir=/execution
        - init 
        - /execution/genesis-poa.json
        volumeMounts:
        - name: shared-data
          mountPath: "/execution/"

      containers:
      - name: geth
        image: docker.io/ethereum/client-go:v1.13.13
        # command:
        # - sh
        # - -c
        # - sleep 3600
        args:
        # - --bootnodes=`cat /execution/enode.txt`
        - --bootnodes=enr:-Jy4QB1V0Hiy44Mrr6J7ZLCUWYopYDxG3nbl8CiU8O5vlg6zP9B0ziSW8MFsQZK2PEr9QVY9e0rFTPgiZJ_kCi8l_HWGAY6lxpwMg2V0aMfGhANBT1WAgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQP5GnblLmN7NHniDy5Ffd2Hlj0N7gh-awAA6dn0VlPhrIRzbmFwwIN0Y3CCdl8
        - --http
        - --http.addr=0.0.0.0
        - --http.api=admin,clique,debug,engine,eth,miner,net,rpc,txpool,web3
        - --http.corsdomain=*
        - --http.port=8545
        - --http.vhosts=*
        - --ws
        - --ws.api=admin,clique,debug,engine,eth,miner,net,rpc,txpool,web3
        - --ws.addr=0.0.0.0
        - --ws.port=8546
        - --ws.origins=*
        - --authrpc.vhosts=*
        - --authrpc.addr=0.0.0.0
        - --authrpc.port=8551
        - --datadir=/execution
        - --allow-insecure-unlock
        - --unlock=0x123463a4b065722e99115d6c222f267d9cabb524
        - --password=/execution/geth_password.txt
        - --nodiscover
        - --syncmode=full
        - --metrics
        - --metrics.addr=0.0.0.0
        - --metrics.port=6060
        - --metrics.expensive
        ports:
        - name: http-endpoint
          containerPort: 8545
        - name: ws-endpoint
          containerPort: 8546
        - name: auth-rpc
          containerPort: 8551
        - name: metrics
          containerPort: 6060
        - name: listener
          containerPort: 30303
          protocol: TCP
        - name: discovery
          containerPort: 30303
          protocol: UDP
        volumeMounts:
        - name: shared-data
          mountPath: "/execution/"
        resources:
          limits: 
            memory: "1Gi"
            cpu: "1000m"

      volumes:
      - name: shared-data
        emptyDir: {}
      - name: shared-data-between-geth-nodes
        persistentVolumeClaim:
          claimName: geth-nodes-pvc
            